### ISSUE TITLE
Multithreading issues in `getkyo/kyo`

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#4265]
See https://github.com/getkyo/kyo/pull/1088

**Comment by WojciechMazur** [comment]
I thoght that most of observed issues in `kyo` were related to lack of proper multithreading support in `scalatest`, after building and using https://github.com/scalatest/scalatest/pull/2359 locally it no longer deadlocks.  
Previously when running locally it was actually running `kyo.ParseTest` and `kyo.AspectTest`, the `all test have passed` observed in CI was confusing as it probably originated from other sub-project tests. 
I've seen some segmentation faults and I'll be trying to debug these. 

The upgrade required me to also upgrade SN to 0.5.7. I've tried to use this version without scalatest upgrade and it also has not deadlocked, so maybe the issue was fixed in SN already. I've also observed crash in this scenario. I'll be conducting more checks tomorrow

**Comment by fwbrasil** [comment]
An update: I've tried enabling tests again with SN `0.5.7`  and scalatest `3.2.19`. The build still failed but at least there's a more informative stack trace now. Note the `ConcurrentModificationException` cause in the trace. @WojciechMazur should we expect that https://github.com/scalameta/scalafmt/pull/4878 might fix it? This is getting more critical for the project as we approach the 1.0-RC cycle. We might need to disable the publishing of native artifacts since we can't test them properly.

https://github.com/getkyo/kyo/actions/runs/14678562565/job/41198293831?pr=1159#step:8:10232
```
[error] scala.scalanative.testinterface.common.RPCCore$ClosedException: java.lang.AssertionError: Fatal failure in tests execution. Aborting all test runs.
[error] 	at scala.scalanative.testinterface.common.RPCCore.helpClose(RPCCore.scala:216)
[error] 	at scala.scalanative.testinterface.common.RPCCore.close(RPCCore.scala:207)
[error] 	at scala.scalanative.testinterface.NativeRunnerRPC.close(NativeRunnerRPC.scala:54)
[error] 	at scala.scalanative.testinterface.adapter.TestAdapter.$anonfun$stopEverything$1(TestAdapter.scala:87)
[error] 	at scala.scalanative.testinterface.adapter.TestAdapter.$anonfun$stopEverything$1$adapted(TestAdapter.scala:87)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:214)
[error] 	at scala.scalanative.testinterface.adapter.TestAdapter.stopEverything(TestAdapter.scala:87)
[error] 	at scala.scalanative.testinterface.adapter.TestAdapter.reportFailure(TestAdapter.scala:81)
[error] 	at scala.scalanative.testinterface.adapter.TestAdapter.$anonfun$executionContext$1(TestAdapter.scala:37)
[error] 	at scala.scalanative.testinterface.adapter.TestAdapter.$anonfun$executionContext$1$adapted(TestAdapter.scala:37)
[error] 	at scala.concurrent.impl.ExecutionContextImpl.reportFailure(ExecutionContextImpl.scala:25)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:74)
[error] 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
[error] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[error] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[error] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[error] Caused by: java.lang.AssertionError: Fatal failure in tests execution. Aborting all test runs.
[error] 	at scala.scalanative.testinterface.adapter.TestAdapter.reportFailure(TestAdapter.scala:78)
[error] 	at scala.scalanative.testinterface.adapter.TestAdapter.$anonfun$executionContext$1(TestAdapter.scala:37)
[error] 	at scala.scalanative.testinterface.adapter.TestAdapter.$anonfun$executionContext$1$adapted(TestAdapter.scala:37)
[error] 	at scala.concurrent.impl.ExecutionContextImpl.reportFailure(ExecutionContextImpl.scala:25)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:74)
[error] 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
[error] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[error] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[error] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[error] Caused by: java.util.ConcurrentModificationException
[error] 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605)
[error] 	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1628)
[error] 	at scala.scalanative.testinterface.common.RPCCore.helpClose(RPCCore.scala:223)
[error] 	at scala.scalanative.testinterface.common.RPCCore.close(RPCCore.scala:207)
[error] 	at scala.scalanative.testinterface.NativeRunnerRPC.close(NativeRunnerRPC.scala:54)
[error] 	at scala.scalanative.testinterface.NativeRunnerRPC.$anonfun$new$1(NativeRunnerRPC.scala:43)
[error] 	at scala.scalanative.testinterface.NativeRunnerRPC.$anonfun$new$1$adapted(NativeRunnerRPC.scala:42)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:74)
[error] 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
[error] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
[error] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
[error] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[error] (kyo-combinatorsNative / Test / testQuick) sbt.TestsFailedException: Tests unsuccessful
[error] (kyo-combinatorsNative / Test / testQuick) scala.scalanative.testinterface.common.RPCCore$ClosedException: java.lang.AssertionError: Fatal failure in tests execution. Aborting all test runs.
```

**Comment by He-Pin** [comment]
maybe just change it to Concurrenthashmap ?

**Comment by fwbrasil** [comment]
Good point. Looking at the code, making this map concurrent might be a fix:

https://github.com/scala-native/scala-native/blob/cb2be72b1e8e2f20f11e2bab7667a3d73e504766/test-interface-common/src/main/scala/scala/scalanative/testinterface/common/RPCCore.scala#L29

**Comment by LeeTibbert** [comment]
@fwbrasil 

To help with triage & work prioritization, may I inquire if this Issue is still a concern for kyo?  
Thank you.

**Comment by fwbrasil** [comment]
hi @LeeTibbert, thanks for checking! I'm not sure if it's exactly the same issue but we attempted to enable Scala Native and still had issues with multi threading. It seems some concurrency issue with the test executor

**Comment by ekrich** [comment]
@fwbrasil It looks like the `ConcurrentHashMap` fix is in. Has that been tested?

**Comment by LeeTibbert** [comment]
@fwbrasil & @ekrich    Thank you for the updates.

As a result of my trying to fix SN Issue #4442, I hope to be cloning the `kyo` repository and
seeing how its tests work for me, particularly kyo being modified to use a local copy of SN PR #4450.

Funny how in software it is hard to get a good stressor, but they come so easily in Real Life.

**Comment by LeeTibbert** [comment]
I've been monitoring the kyo repository since fwbrasil reported that recent scala native
builds have been succeeding.  As a checkpoint, I believe kyo is currently using  SN version 0.5.10.
(I do not know if 0.5.9 worked for kyo or not)

There have been a number of kyo builds over the past month or  so.  That  repository is pretty active.
I have not checked  the SN results of every build, but have spot  checked many.

Based on that evidence, and lacking an objection from any kyo devo, I believe that  this Issue
can be closed "without prejudice", meaning  that another Issue can be opened if anybody
discovers a problem with kyo and Scala Native.

Some things do get better over time.
